[package]
name = "rust_sessions"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
log = "0.4"
env_logger = "0.10"
tracing = "0.1"
tracing-subscriber = "0.3"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
rand = "0.9.1"
csv = "1.3.1"
